todo_list/base/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView, CustomLoginView, RegisterPage, LogoutView


urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('', TaskList.as_view(), name='tasks'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),

]

todo_list/todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

todo_list/base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    usuário = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    título = models.CharField(max_length=200, null=True, blank=True)
    descrição = models.TextField(null=True, blank=True)
    completa = models.BooleanField(default=False)
    criar = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.título:
            return self.título
        else:
            return "Tarefa Sem Título"
    
    class Meta:
        ordering = ['completa']

todo_list/base/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout
from django.views.generic import RedirectView
from .models import Task


class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('tasks')

class LogoutView(RedirectView):
    url = '/login'

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return super().dispatch(request, *args, **kwargs)


class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        usuário = form.save()
        if usuário is not None:
            login(self.request, usuário)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(usuário=self.request.user)
        context['count'] = context['tasks'].filter(completa=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(título__startswith=
                                                       search_input)
            
        context['search_input'] = search_input

        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['título', 'descrição', 'completa']
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        form.instance.usuário = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['título', 'descrição', 'completa']
    success_url = reverse_lazy('tasks')


class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('tasks')

todo_list/base/templates/base/login.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <h1 style="text-align: center;">Login</h1>
    </div>
</div>

<form method="POST">
    {% csrf_token %}
    <div>
        <label for="id_username">Usuário:</label>
        
        {{ form.username }}
    </div>
    <div>
        <label for="id_password">Senha:</label>
        
        {{ form.password }}
    </div>
    <br>
    <input class="button" type="submit" value="Login">
</form>

<p>Não possui uma conta? <a href="{% url 'register' %}">Registre-se</a></p>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.querySelector("[name='username']").classList.add("button");
        document.querySelector("[name='password']").classList.add("button");
    });
</script>


<style>
    .header-message {
        background-color: #549CC6;
        color: #E7E6E1;
        padding: 15px 0; 
        text-align: center;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 999; 
    }

    .header-message p {
        font-size: 48px; 
        margin: 0;
        line-height: 50px; 
        text-decoration: none;
    }

    .header-message a {
        text-decoration: none;
    }
</style>
<body>
    <div class="header-message">
        <p><a href="{% url 'login' %}">ToDo List</a></p>
    </div>
</body>

{% endblock content %}

todo_list/base/templates/base/main.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo List</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@700&display=swap" rel="stylesheet">

    <style>
        body {
            background-color: #E7E6E1;
            font-family: "Rubik", sans-serif;
            font-optical-sizing: auto;
            font-weight: 700;
            font-style: normal;
            display: flex;
            justify-content: center; 
            align-items: center; 
            min-height: 100vh; 
            margin: 0; 
            position: relative;
        }

        a,
        p {
            color: #E7E6E1
        }

        .container {
            max-width: 550px;
            background-color: #457FA2;
            color: #E7E6E1;
            padding: 20px;
            border-radius: 20px;
            box-shadow: 2px 2px 100px -4px rgba(0, 0, 0, 0.21);
        }

        /* Barra superior */
        body::before {
            content: "";
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 80px;
            background-color: #549CC6;
        }

        /* Barra inferior */
        body::after {
            content: "";
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 100px;
            background-color: #457FA2;
        }

        .header-bar {
            background-color: #549CC6;
            padding: 20px;
            border-radius: 20px;
            width: calc(100% - 40px);
            text-decoration: none;
        }


        .header-bar a {
            color: rgb(247, 247, 247);
            text-decoration: none;
        }

        
        .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px;
            background-color: #457FA2;
            border-top: 1px solid #E7E6E1;
            border-bottom: 1px solid #E7E6E1;
        }
        

        .task-title {
            display: flex;
        }

        .task-title a {
            text-decoration: none;
            color: #E7E6E1;
            margin-left: 1px;
        }

        .task-complete-icon {
            height: 15px;
            width: 15px;
            background-color: green;
            border-radius: 50%;
            margin-right: 5px;
        }

        .task-incomplete-icon {
            height: 15px;
            width: 15px;
            background-color: #E7E6E1;
            border-radius: 50%;
            margin-right: 5px;
        }

        .delete-link {
            text-decoration: none;
            font-weight: 700;
            color: red;
            font-size: 25px;
            line-height: 0;
            display: flex;
            margin-left: 5px;
            
        }

        #search-add-wrapper {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            border-radius: 5px;
        }

        #add-link {
            color: #E7E6E1;
            text-decoration: none;
            font-size: 45px;
            margin-top: 15px;
            display: flex;
        }

        input[type=text]
        input[type=password]
        textarea {
            border: 2px solid #E7E6E1;
            border-radius: 15px;
            padding: 7px;
            width: 90%;
        }

        label {
            padding-top: 10px !important;
            display: block;
        }

        .button {
            border: 3px solid #E7E6E1;
            background-color: #457FA2;
            color: #E7E6E1;
            padding: 7px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }

        .card-body {
            padding: 20px;
        }


    </style>
</head>

<body>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
</body>

</html>

todo_list/base/templates/base/register.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <h1 style="text-align: center;">Registre-se</h1>
    </div>
</div>

<form method="POST">
    {% csrf_token %}
    <div>
        <label for="id_username">Usuário:</label>
        {{ form.username }}
        <p>Obrigatório. 150 caracteres ou menos. Somente letras, dígitos e @/./+/-/_.</p>
    </div>
    <div>
        <label for="id_password1">Senha:</label>
        {{ form.password1 }}
    </div>
    <div>
        <label for="id_password2">Confirme a senha:</label>
        {{ form.password2 }}
        <p>
            Sua senha não pode ser muito semelhante ao seu usuário.<br>
            Sua senha deve conter pelo menos 8 caracteres.<br>
            Sua senha não pode ser uma senha comumente usada.<br>
            Sua senha não pode ser totalmente numérica.
        </p>
    </div>
    
    <input class="button" type="submit" value="Registrar">
</form>

<p>Já possui uma conta? <a href="{% url 'login' %}">Login</a></p>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.querySelector("[name='username']").classList.add("button");
        document.querySelector("[name='password1']").classList.add("button");
        document.querySelector("[name='password2']").classList.add("button");
    });
</script>


<style>
    .header-message {
        background-color: #549CC6;
        color: #E7E6E1;
        padding: 15px 0; 
        text-align: center;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 999; 
    }

    .header-message a {
        font-size: 48px; 
        margin: 0;
        line-height: 50px; 
        text-decoration: none;
    }
</style>
<body>
    <div class="header-message">
        <p><a href="{% url 'login' %}">ToDo List</a></p>
    </div>
</body>


{% endblock content %}

todo_list/base/templates/base/task.html
{% extends 'base/main.html' %}
{% block content %}

<h1>ToDo List</h1>
<hr>
<h1>Tarefa: {{task}}</h1>
<h1>Detalhes: </h1>
<p>{{task.descrição}}</p>

{% endblock content %}

todo_list/base/templates/base/task_confirm_delete.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <a href="{% url 'tasks' %}">&#8592; Voltar</a>
    </div>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Tem certeza, que deseja apagar a tarefa "{{task}}"?</p>
        <input class="button" type="submit" value="Apagar">
    </form>
</div>


<style>
    .header-message {
        background-color: #549CC6;
        color: #E7E6E1;
        padding: 15px 0; 
        text-align: center;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 999; 
    }

    .header-message p {
        font-size: 48px; 
        margin: 0;
        line-height: 50px; 

    }

    .header-message a {
        text-decoration: none;
    }
</style>
<body>
    <div class="header-message">
        <p><a href="{% url 'tasks' %}">ToDo List</a></p>
    </div>
</body>


{% endblock content %}

todo_list/base/templates/base/task_form.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <a href="{% url 'tasks' %}">&#8592; Voltar</a>
        <h1 style="text-align: center;">Editor de Tarefas</h1>
    </div>
</div>

<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        <div>
            <label for="id_título">Título:</label>
            {{ form.título }}
        </div>
        <div>
            <br><label for="id_descrição">Descrição:</label>
            {{ form.descrição }}
        </div>
        <div style="text-align: center;">
            <label for="id_completa" style="display: inline-block; width: 100px; text-align: right; margin-right: 1px;">Completa</label>
            {{ form.completa }}
        </div>
        <br><input class="button" type="submit" value="Criar"> 
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.querySelector("[name='título']").classList.add("button");
        document.querySelector("[name='descrição']").classList.add("button");
    });
</script>


<style>
    .header-message {
        background-color: #549CC6;
        color: #E7E6E1;
        padding: 15px 0; 
        text-align: center;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 999; 
    }

    .header-message p {
        font-size: 48px; 
        margin: 0;
        line-height: 50px; 

    }

    .header-message a {
        text-decoration: none
    }
    
</style>
<body>
    <div class="header-message">
        <p><a href="{% url 'tasks' %}">ToDo List</a></p>
    </div>
</body>


{% endblock content %}

todo_list/base/templates/base/task_list.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <div>
        {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a> {% else %}
        <a href="{% url 'login' %}">Login</a> {% endif %}
        <h1 style="text-align: center;">ToDo List</h1>
    </div>
</div>


<div id="search-add-wrapper">
    <form method="GET" style="margin-top: 20px;display: flex;">
        <input class="button" type="text" name="search-area" value="{{search_input}}">
        <input class="button" type="submit" value="&#128269;">
    </form>
    <a id="add-link" href="{% url 'task-create' %}">&#x2b;</a>
</div>


<hr>
<h3 style="text-align: center;">Você tem {{count}} tarefa{{ count|pluralize:"s" }} incompleta{{ count|pluralize:"s" }}!</h3>
<div class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper">
        {% if task.completa %}
        <div class="task-title">
            <div class="task-complete-icon"></div>
            <i><s><a href="{% url 'task-update' task.id %}">{{task}}</a></s></i>
        </div>
        <a class="delete-link" href="{%url 'task-delete' task.id %}">&#215;</a>
        {% else %}
        <div class="task-title">
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'task-update' task.id %}">{{task}}</a>
        </div>
        <a class="delete-link" href="{%url 'task-delete' task.id %}">&#215;</a>
        {% endif %}
    </div>

    {% empty %}
    <h3>Lista de tarefas vazia!</h3>
    {% endfor %}

    <style>
        .header-message {
            background-color: #549CC6;
            color: #E7E6E1;
            padding: 15px 0; 
            text-align: center;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            z-index: 999; 
        }

        .header-message p {
            font-size: 32px; 
            margin: 0;
            line-height: 50px; 

        }
    </style>
    <body>
        <div class="header-message">
            <p>Bem vindo, {{request.user}}!</p>
        </div>
    </body>
</div>

{% endblock content %}